### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by skasperski** [agv-polsl/ekf-ahrs#44]
Hello,

I am using this lib for an integrated IMU and have some questions about it. The filter results where not as good as I exected them too be, so I looked a bit into the code.

- I am confused about the [Ahrs::calc_euler_angles_rates](https://github.com/agv-polsl/kalman-ahrs/blob/master/src/ahrs.cpp#L113) method. Isn't the `roll_rate = gyro_read.x` and `pitch_rate = gyro_read.y`?
- Was there a specific reason not to use `gyro_read.z` for the prediction of the yaw angle?
- Does the lib cap all angles at +/- 90°? If I turn it upside down around any axes, the filter will just move back to identy. E.g. the Z-Axis will always point upwards, even when upside down.

Thanks in advance,
Sebastian

**Comment by maciejzj** [comment]
Hi!
It's been a long time since I've been working on this, so I neither remember the code well, nor the actual IMU related-stuff.

From what I remember, the code worked somewhat ok, however it definitely wasn't the best IMU system in the world. You can use it as a starting point and develop something better, there is a lot of room for improvement.

> I am confused about the [Ahrs::calc_euler_angles_rates](https://github.com/agv-polsl/kalman-ahrs/blob/master/src/ahrs.cpp#L113) method. Isn't the roll_rate = gyro_read.x and pitch_rate = gyro_read.y?

As said, I barely remember this stuff, but I believe angular velocities and euler angle rates are not exactly the same. Here is the formula I have used: https://robotics.stackexchange.com/a/9510 with a tiny bit of explanation. You can delve into this topic more. From what I remember gyro readouts are relative to coordinates system attached to the body, while Euler angles (and their derivatives) are relative to an absolute coordinates system.

> Was there a specific reason not to use gyro_read.z for the prediction of the yaw angle?

Again, barely remember anything here. Pitch and Yaw can be calculated from accelerometers and gyros because there is a way to relate them to acceleration of gravity. There is no way to do this for yaw. For this reason I rely mainly on magnetometer for yaw, however it uses gyro readouts for corrections too.

> Does the lib cap all angles at +/- 90°? If I turn it upside down around any axes, the filter will just move back to identy. E.g. the Z-Axis will always point upwards, even when upside down.

From what I remember this may be true. Maybe this is due to using euler angles-based formulas instead of quaternions.

I remember this stuff very vaguely, so take this answer with a (big) pinch of salt. Good luck :)

**Comment by skasperski** [comment]
Thanks for the quick answer, that already gave me some context from where this formula is coming. Although I do not quite get the linked answer either. Maybe there are different types of gyroscopes? I would disagree with the answer on SO and say that a gyro gives you angular velocities (dRoll, dPitch, dYaw) in rad/second, but who knows.

Best regards,
Sebastian
